version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  node1:
    image: node_1
    network_mode: "host"
    ports:
      - "12345:12365"
    volumes:
      - /home/ltsu/Desktop/ds_proj2/DistributedSystems_project/node_1_sensors/db:/data
